apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: tmate-master
        image: tmate/tmate-master:latest
        env:
        # - name: INTERNAL_API_AUTH_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: misc
        #       key: wsapi_key
        - name: ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: misc
              key: erl_cookie
        - name: ERL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MASTER_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: master_base_url
        ports:
        - containerPort: 4000
          name: http
        - containerPort: 9100
          name: metrics
---
kind: Service
apiVersion: v1
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - port: 4000
    name: http
  - port: 9100
    name: metrics
