# kubectl delete secret basic-auth
# kubectl create secret generic basic-auth \
# --from-literal=auth=$(LOGIN=ii ; PASSWORD=ii ; echo $PASSWORD | htpasswd -i -n $LOGIN)
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  auth: aWk6JGFwcjEkZ09qVnEzS3gkZVdHREd3WDhUU3JxU2p0cjVBamdJMA==
